trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'  
stages:
- stage: BuildStage
  displayName: 'Stage - Build'
  jobs:
  - job: Checkout
    steps:
    - checkout: self
      displayName: 'Checkout code from main branch'
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Install .Net Core SDK'
      inputs:
        version: '8.0.0'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
  - job: RestoreNuGetPackages
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
      displayName: ' Restore NuGet Packages'
 